spring.application.name=backend
spring.jackson.property-naming-strategy=SNAKE_CASE
stashes.path=/root/stashes
stashes.meta.path=/root/stashes-meta

# Logging Configuration
logging.level.root=INFO
logging.level.com=TRACE
