spring.application.name=backend
spring.jackson.property-naming-strategy=SNAKE_CASE
stashes.path=./backend-data/stashes
stashes.meta.path=./backend-data/stashes-meta

# Logging Configuration
logging.level.root=INFO
logging.level.com=TRACE